// AUTO-GENERATED from TruMedia's public stat dictionary (Google Sheet).
// Curated to clean, aggregate, player-applicable stats (no opponent |OPP mirrors,
// no team-only summary/salary scopes). Each abbrev is a TruMedia column code used
// in customQuery columns=[abbrev]. label/category drive the UI grouping.
// Regenerate by re-running the dictionary export + curation (see replit.md gotchas).

export type TrumediaStatDef = { abbrev: string; label: string; category: string };

export const TRUMEDIA_STATS: TrumediaStatDef[] = [
  { abbrev: "10PlDr", label: "10 or More Play Drives", category: "offense" },
  { abbrev: "1HPPG", label: "First Half Points Per Game", category: "offense" },
  { abbrev: "1HPts", label: "Points Scored In First Half", category: "offense" },
  { abbrev: "1orTD", label: "First Downs Or Touchdowns", category: "offense" },
  { abbrev: "1QPPG", label: "First Quarter Points Per Game", category: "offense" },
  { abbrev: "1QPts", label: "Points Scored In First Quarter", category: "offense" },
  { abbrev: "1st2ndDwn", label: "1st/2nd Down Plays", category: "offense" },
  { abbrev: "1stAtt", label: "First Down Pass Attempts", category: "passing" },
  { abbrev: "1stDn", label: "First Downs", category: "offense" },
  { abbrev: "1stDwnYPR", label: "1st Down Yards per Rush", category: "rushing" },
  { abbrev: "1stHalfYPR", label: "1st Half Yards per Rush", category: "rushing" },
  { abbrev: "1stPl", label: "First Down Plays", category: "offense" },
  { abbrev: "1stRush", label: "First Down Rushes", category: "rushing" },
  { abbrev: "1stSack", label: "First Down Sacks", category: "passing" },
  { abbrev: "2HPPG", label: "Second Half Points Per Game", category: "offense" },
  { abbrev: "2HPts", label: "Points Scored In Second Half", category: "offense" },
  { abbrev: "2ndHalfYPR", label: "2nd Half Yards per Rush", category: "rushing" },
  { abbrev: "2PTAPenaltyEPA", label: "Two Point Attempt Penalty EPA", category: "specialteams" },
  { abbrev: "2PTAPenCmtdEPA", label: "Two Point Attempt Penalties Committed EPA", category: "specialteams" },
  { abbrev: "2PtAt", label: "Two Point Conversion Attempts", category: "offense" },
  { abbrev: "2PtCv", label: "Two Point Conversions Made", category: "offense" },
  { abbrev: "2PtDefEPA", label: "2 Point Attempt Defensive EPA", category: "defense" },
  { abbrev: "2PtOffEPA", label: "2 Point Attempt Offensive EPA", category: "offense" },
  { abbrev: "2PtPsAtt", label: "Two-Point Pass Attempt", category: "offense" },
  { abbrev: "2PtPsCv", label: "Two-Point Pass Conversion", category: "offense" },
  { abbrev: "2PtRecCv", label: "Reception on Successful Two-Point Conversion Attempt", category: "receiving" },
  { abbrev: "2PtRsh", label: "Two-Point Rush Attempt", category: "offense" },
  { abbrev: "2PtRshCv", label: "Two-Point Rush Conversion", category: "offense" },
  { abbrev: "2QPPG", label: "Second Quarter Points Per Game", category: "offense" },
  { abbrev: "2QPts", label: "Points Scored in Second Quarter", category: "offense" },
  { abbrev: "3DPlayPct", label: "Percentage Of Plays That Are 3rd Down", category: "offense" },
  { abbrev: "3PlDr", label: "3 or Less Play Drives", category: "offense" },
  { abbrev: "3QPPG", label: "Third Quarter Points Per Game", category: "offense" },
  { abbrev: "3QPts", label: "Points Scored in Third Quarter", category: "offense" },
  { abbrev: "3rdAtt", label: "Third Down Conversion Chances", category: "offense" },
  { abbrev: "3rdAvoid", label: "3rd Down Avoidance", category: "offense" },
  { abbrev: "3rdAvoidD", label: "3rd Down Avoidance on Defense", category: "defense" },
  { abbrev: "3rdCv", label: "Third Down Conversions", category: "offense" },
  { abbrev: "3rdDistTo1st", label: "Average Distance to First Down on Third Down", category: "offense" },
  { abbrev: "3rdLongAtt", label: "Third And >=7 Attempts", category: "offense" },
  { abbrev: "3rdLongCv", label: "Third And >=7 Conversions", category: "offense" },
  { abbrev: "3rdMedAtt", label: "Third And Between 4 And 6 Attempts", category: "offense" },
  { abbrev: "3rdMedCv", label: "Third And Between 4 And 6 Conversions", category: "offense" },
  { abbrev: "3rdShortAtt", label: "Third And <=3 Attempts", category: "offense" },
  { abbrev: "3rdShortCv", label: "Third And <=3 Conversions", category: "offense" },
  { abbrev: "3rdShrtYPR", label: "3rd and Short Yards per Rush", category: "rushing" },
  { abbrev: "4QPPG", label: "Fourth Quarter Points Per Game", category: "offense" },
  { abbrev: "4QPts", label: "Points Scored In Fourth Quarter", category: "offense" },
  { abbrev: "4thAtt", label: "Fourth Down Conversion Chances", category: "offense" },
  { abbrev: "4thCv", label: "Fourth Down Conversions", category: "offense" },
  { abbrev: "4thDecisions", label: "Number Of 4th Down Decisions Made", category: "offense" },
  { abbrev: "4thDown_-1to_-29", label: "Number Of 4th Down Decisions Made between the -1 to -29", category: "overall" },
  { abbrev: "4thDown_-30to_-49", label: "Number Of 4th Down Decisions Made between the -30 to -49", category: "overall" },
  { abbrev: "60YdDr", label: "60+ Yard Drives", category: "offense" },
  { abbrev: "80YdDr", label: "80+ Yard Drives", category: "offense" },
  { abbrev: "AirYds", label: "Air Yards", category: "passing" },
  { abbrev: "AirYdsRec", label: "Air Yards as a Receiver", category: "receiving" },
  { abbrev: "All_Converted_1st_Downs", label: "Any Offensive Play Converted for an Earned 1st Down", category: "offense" },
  { abbrev: "All_Converted_1st_Downs_Allowed", label: "Any Defensive Play Converted for an Earned 1st Down for Offense", category: "defense" },
  { abbrev: "APYds", label: "All Purpose Yards", category: "offense" },
  { abbrev: "Ast", label: "Assisted Defensive Tackles", category: "defense" },
  { abbrev: "Att", label: "Pass Attempts", category: "passing" },
  { abbrev: "Att2.5-3Sec", label: "Pass Attempts With 2.5 Seconds to 3 Seconds To Throw", category: "passing" },
  { abbrev: "Att2.5Sec", label: "Pass Attempts With Under 2.5 Seconds To Throw", category: "passing" },
  { abbrev: "AttAYNeg0", label: "Attempts at or Behind LOS", category: "passing" },
  { abbrev: "AttRB", label: "Pass Attempts to Running Backs", category: "passing" },
  { abbrev: "AttTar", label: "QB Pass Attempts with a Target", category: "passing" },
  { abbrev: "AttTE", label: "Pass Attempts to Tight Ends", category: "passing" },
  { abbrev: "AttWR", label: "Pass Attempts to Wide Receivers", category: "passing" },
  { abbrev: "Avg3rdDistDef", label: "Average 3rd Down Distance to Go on Defense", category: "defense" },
  { abbrev: "AvgAYToStx", label: "Average Air Yards Per Attempt Relative To First Down Line (Positive=Past FD Line)", category: "passing" },
  { abbrev: "AvgDistTo1st", label: "Average Distance To First Down", category: "offense" },
  { abbrev: "AvgFGA", label: "Average FG Attempt Distance", category: "kicking" },
  { abbrev: "AvgGainPerTkl", label: "Average Offense Yards Gained When Player Made The Tackle", category: "defense" },
  { abbrev: "AvgSP", label: "Offensive Average Starting Field Position", category: "offense" },
  { abbrev: "AvgTimeToSack", label: "Average Time To Sack", category: "defense" },
  { abbrev: "AvgTimeToSackAllwd", label: "Average Time To Sack Allowed", category: "passing" },
  { abbrev: "AvgTimeToThrow", label: "Average Time To Throw Or Sack On Dropbacks", category: "passing" },
  { abbrev: "AYTS3rd", label: "Amount of air yards in front or behind the first down marker per 3rd down pass attempts", category: "passing" },
  { abbrev: "BFGTD", label: "Blocked FGA Touchdowns", category: "specialteams" },
  { abbrev: "BlFGTD", label: "Blocked FGA Touchdowns", category: "kicking" },
  { abbrev: "Blitzed", label: "Dropbacks Versus Blitz", category: "passing" },
  { abbrev: "BlkKck", label: "Opponent Kicks Blocked", category: "kicking" },
  { abbrev: "BlkKckTD", label: "Touchdowns on Blocked Field Goals or Punts", category: "returns" },
  { abbrev: "BlkP", label: "Opponent Punts Blocked", category: "punting" },
  { abbrev: "BlkTD1stScr", label: "Blocked Field Goal and Blocked Punt Touchdowns That Were the 1st Score of the Game", category: "specialteams" },
  { abbrev: "BlkXP", label: "Opponent Extra Point Blocked", category: "kicking" },
  { abbrev: "BlPTD", label: "Blocked Punt Touchdowns", category: "returns" },
  { abbrev: "BoxLOS", label: "Snaps When Defender Lined Up In Box At LOS", category: "defense" },
  { abbrev: "BPTD", label: "Blocked Punt Touchdowns", category: "returns" },
  { abbrev: "Cmp", label: "Pass Completions", category: "passing" },
  { abbrev: "CmpPG", label: "Pass Completions Per Game", category: "passing" },
  { abbrev: "Coverage", label: "Defensive Plays in Pass Coverage", category: "passcoverage" },
  { abbrev: "CvDst", label: "Average Conversion Distance", category: "offense" },
  { abbrev: "CvgSnap", label: "Snaps In Pass Coverage", category: "passcoverage" },
  { abbrev: "DecisionEPA", label: "Points Added From 4th Down Decision", category: "offense" },
  { abbrev: "Def4thMA", label: "Defensive 4th Down Makes - Attempts", category: "defense" },
  { abbrev: "DefAbortedEPA", label: "Defensive Aborted EPA", category: "defense" },
  { abbrev: "DefConvDown", label: "Defense Conversion Down %", category: "defense" },
  { abbrev: "DefFmbLEPA", label: "Defensive Fumble Lost EPA", category: "defense" },
  { abbrev: "DefIntEPA", label: "Defensive Interception EPA", category: "passcoverage" },
  { abbrev: "DefPassEPA", label: "Defensive EPA on Designed Pass Plays", category: "defense" },
  { abbrev: "DefPassPenaltyEPA", label: "Defensive Pass Penalty EPA", category: "defense" },
  { abbrev: "DefPassPenCmtdEPA", label: "Defensive Pass Penalties Committed EPA", category: "defense" },
  { abbrev: "DefPassSackEPA", label: "Defensive Sacked EPA", category: "defense" },
  { abbrev: "DefPassScrambleEPA", label: "Defensive Scramble EPA", category: "defense" },
  { abbrev: "DefPassSpikeEPA", label: "Defensive Spike EPA", category: "defense" },
  { abbrev: "DefPassThrowEPA", label: "Defensive Throw EPA", category: "defense" },
  { abbrev: "DefPenaltyEPA", label: "Defensive Penalty EPA", category: "defense" },
  { abbrev: "DefPenCmtdEPA", label: "Defensive Penalties Committed EPA", category: "defense" },
  { abbrev: "DefPnYds", label: "Defensive Penalty Yards", category: "defense" },
  { abbrev: "DefPreSnapPenaltyEPA", label: "Defensive Pre Snap Penalty EPA", category: "defense" },
  { abbrev: "DefPreSnapPenCmtdEPA", label: "Defensive Pre Snap Penalties Committed EPA", category: "defense" },
  { abbrev: "DefQBHit", label: "Defensive QB Hits on Dropbacks", category: "passrush" },
  { abbrev: "DefRunEPA", label: "Defensive EPA on Designed Run Plays", category: "defense" },
  { abbrev: "DefRushEPA", label: "Defensive Rush EPA", category: "defense" },
  { abbrev: "DefRushKneelEPA", label: "Defensive Kneel EPA", category: "defense" },
  { abbrev: "DefRushNotQBEPA", label: "Defensive Non-QB Rush EPA", category: "defense" },
  { abbrev: "DefRushPenaltyEPA", label: "Defensive Rush Penalty EPA", category: "defense" },
  { abbrev: "DefRushPenCmtdEPA", label: "Defensive Rush Penalties Committed EPA", category: "defense" },
  { abbrev: "DefSuccess", label: "Successful Play Count on Defense", category: "defense" },
  { abbrev: "DefTD", label: "Defensive Touchdowns", category: "defense" },
  { abbrev: "DefTD1stScr", label: "Defensive Touchdowns That Were the 1st Score of the Game", category: "defense" },
  { abbrev: "DefTotalEPA", label: "Defensive EPA", category: "defense" },
  { abbrev: "DefTotalPassEPA", label: "Defensive Total Pass EPA", category: "defense" },
  { abbrev: "DefTotalRunEPA", label: "Defensive Total Run EPA", category: "defense" },
  { abbrev: "DefTotalRushEPA", label: "Defensive Total Rush EPA", category: "defense" },
  { abbrev: "DefTovEPA", label: "Defensive Turnover EPA", category: "defense" },
  { abbrev: "DefTrgManCov", label: "Snaps as Primary Defender in Coverage w/ Man Coverage", category: "defense" },
  { abbrev: "DefXP", label: "Defensive Conversions", category: "defense" },
  { abbrev: "DesRush", label: "Designed Rushes", category: "rushing" },
  { abbrev: "DfFF", label: "Defensive Forced Fumbles", category: "defense" },
  { abbrev: "DfFR", label: "Defensive Fumble Recoveries", category: "defense" },
  { abbrev: "DfPen", label: "Defensive Penalties", category: "defense" },
  { abbrev: "DfPenNoPlay", label: "Defensive penalties in presnap or deadball situations", category: "defense" },
  { abbrev: "DfPenPassPl", label: "Defensive penalties on pass plays", category: "defense" },
  { abbrev: "DfPenRushPl", label: "Defensive penalties on rush plays", category: "defense" },
  { abbrev: "DfSnap", label: "Defensive Snaps", category: "defense" },
  { abbrev: "DfSnapWithPen", label: "Defensive Snaps Including Penalties", category: "defense" },
  { abbrev: "DfTFL", label: "Tackle for a Loss", category: "defense" },
  { abbrev: "DfTkl", label: "Defensive Tackles", category: "defense" },
  { abbrev: "DInt", label: "Defensive Interceptions", category: "passcoverage" },
  { abbrev: "DPIDrawn", label: "Opponent Defensive Pass Interference Penalties Drawn", category: "receiving" },
  { abbrev: "DPIYdsDrawn", label: "Opponent Defensive Pass Interference Yards Drawn", category: "receiving" },
  { abbrev: "DrftYr", label: "Draft Eligible Season", category: "player" },
  { abbrev: "Drives", label: "Drives", category: "offense" },
  { abbrev: "Drives10Plays", label: "Drives w/ 10+ Plays", category: "offense" },
  { abbrev: "Drpbk", label: "Dropbacks", category: "passing" },
  { abbrev: "Drpbk4Rush", label: "Dropbacks With 4 Or Fewer Pass Rushers", category: "passing" },
  { abbrev: "Drpbk5Rush", label: "Dropbacks With Exactly 5 Pass Rushers", category: "passing" },
  { abbrev: "DrpBkPlusEPA", label: "The number of dropbacks where the result of the play has a greater expected points value than the pr", category: "passing" },
  { abbrev: "DrPG", label: "Drives Per Game", category: "offense" },
  { abbrev: "DSack", label: "Defensive Sacks", category: "passrush" },
  { abbrev: "DSkYds", label: "Defensive Sack Yards", category: "passrush" },
  { abbrev: "DSnapsPass", label: "Defensive Snaps that were pass plays", category: "defense" },
  { abbrev: "DSnapsPsCovg", label: "Defensive snaps in pass coverage", category: "passcoverage" },
  { abbrev: "DSnapsPsRush", label: "Defensive snaps as pass rusher", category: "passrush" },
  { abbrev: "DSnapsRunDefense", label: "Defensive snaps in run defense", category: "rushdefense" },
  { abbrev: "DSSR", label: "Down Set Conversion Rate", category: "offense" },
  { abbrev: "Elig", label: "NCAA Eligibility", category: "player" },
  { abbrev: "EPAOnDB", label: "EPA On Dropbacks", category: "passing" },
  { abbrev: "EPAOnDBOrRsh", label: "EPA On Dropbacks or Designed Rush Attempts", category: "passing" },
  { abbrev: "EPAOnRush", label: "EPA On Designed Rush Attempts (Excludes Scrambles)", category: "rushing" },
  { abbrev: "EPAOnTar", label: "EPA On Targets", category: "receiving" },
  { abbrev: "EPAPerDB", label: "EPA Per Dropback", category: "passing" },
  { abbrev: "EPAPerRush", label: "EPA Per Designed Rush Attempt (Excludes Scrambles)", category: "rushing" },
  { abbrev: "EPAPerTar", label: "EPA Per Target", category: "receiving" },
  { abbrev: "ExplPlay", label: "Explosive Plays", category: "offense" },
  { abbrev: "ExplRec", label: "Explosive Receptions", category: "receiving" },
  { abbrev: "ExplRush", label: "Explosive Rushes", category: "rushing" },
  { abbrev: "EZRecTD", label: "Receiving Touchdowns Caught in the End Zone", category: "receiving" },
  { abbrev: "EZTar", label: "Targets in the End Zone", category: "receiving" },
  { abbrev: "EZTgt", label: "End Zone Targets", category: "receiving" },
  { abbrev: "FairCatchPunt", label: "Fair Catches on Punts", category: "specialteams" },
  { abbrev: "FakePunt", label: "Fake Punts", category: "overall" },
  { abbrev: "FantPPG", label: "Offensive Fantasy Points per Game", category: "offense" },
  { abbrev: "FantPPR", label: "Offensive Fantasy Points", category: "offense" },
  { abbrev: "FantPPRPPG", label: "Offensive Fantasy Points per Game", category: "offense" },
  { abbrev: "FantPts", label: "Offensive Fantasy Points", category: "offense" },
  { abbrev: "FC", label: "Fair Catch", category: "returns" },
  { abbrev: "FC_on_KOR", label: "Fair Catches On Kickoff Returns", category: "specialteams" },
  { abbrev: "FF", label: "Forced Fumble", category: "defense" },
  { abbrev: "FG", label: "Field Goals Made", category: "kicking" },
  { abbrev: "FG_EPA", label: "FG EPA", category: "specialteams" },
  { abbrev: "FG1stScr", label: "Field Goals That Were the 1st Score of the Game", category: "kicking" },
  { abbrev: "FG40", label: "40-49 Yd Field Goals Made", category: "kicking" },
  { abbrev: "FG50", label: "50+ Yd Field Goals Made", category: "kicking" },
  { abbrev: "FGA", label: "Field Goals Attempts", category: "kicking" },
  { abbrev: "FGA40", label: "40-49 Yd Field Goals Attempts", category: "kicking" },
  { abbrev: "FGA50", label: "50+ Yd Field Goals Attempts", category: "kicking" },
  { abbrev: "FGAPenaltyEPA", label: "Field Goal Attempt Penalty EPA", category: "specialteams" },
  { abbrev: "FGAPenCmtdEPA", label: "Field Goal Attempt Penalties Committed EPA", category: "specialteams" },
  { abbrev: "FGBlk", label: "Opponent Field Goals Blocked", category: "kicking" },
  { abbrev: "FGBlkd", label: "FGA Blocked", category: "kicking" },
  { abbrev: "FGKickBlockRetEPA", label: "Opponent FGA EPA", category: "kicking" },
  { abbrev: "FGKickEPA", label: "FGA EPA", category: "kicking" },
  { abbrev: "FGKickerEPA", label: "EPA on FG & XP", category: "specialteams" },
  { abbrev: "FGLg", label: "Longest Field Goal Made (In Yards)", category: "kicking" },
  { abbrev: "FL", label: "Fumbles Lost", category: "offense" },
  { abbrev: "FR", label: "Fumble Recovered", category: "defense" },
  { abbrev: "FRLg", label: "Longest Return of Opponent Fumble (Yards)", category: "defense" },
  { abbrev: "FRLgTD", label: "Longest Return of Opponent Fumble for Touchdown (Yards)", category: "defense" },
  { abbrev: "FRTD", label: "Fumble Recovery Touchdowns", category: "defense" },
  { abbrev: "Fum", label: "Fumbles", category: "offense" },
  { abbrev: "FumRetYdsDef", label: "Defensive Fumble Return Yards", category: "defense" },
  { abbrev: "G2GDr", label: "Goal to Go Drives", category: "offense" },
  { abbrev: "G2GRush", label: "Goal-to-Go Rushes", category: "rushing" },
  { abbrev: "GoalLineRush", label: "Rushes 5 Yards or Fewer from Goal Line", category: "rushing" },
  { abbrev: "GoalLineTD", label: "Touchdowns on Rushes 5 Yards or Fewer from Goal Line", category: "rushing" },
  { abbrev: "GoForIts", label: "Number Of Times Teams Passed Or Rushed On 4th Down", category: "offense" },
  { abbrev: "GPsYd", label: "Gross Passing Yards", category: "passing" },
  { abbrev: "Gun", label: "Shotgun Plays", category: "offense" },
  { abbrev: "Havoc_Rate", label: "% of Defensive Plays w/ TFL, FF, INT, PBU, or Sack", category: "defense" },
  { abbrev: "In-LineTE_Trg", label: "Targets Aligned as an In-Line Tight End", category: "offense" },
  { abbrev: "Incomp", label: "Incompletions On Pass Attempts", category: "passing" },
  { abbrev: "Int", label: "Pass Interceptions", category: "passing" },
  { abbrev: "IRLg", label: "Longest Interception Return (Yards)", category: "passcoverage" },
  { abbrev: "IRTD", label: "Interception Return Touchdowns", category: "passcoverage" },
  { abbrev: "IRYd", label: "Interception Return Yards", category: "passcoverage" },
  { abbrev: "K-Ret", label: "Kickoff Returns", category: "returns" },
  { abbrev: "K-RTD", label: "Kickoff Return Touchdowns", category: "returns" },
  { abbrev: "K-RYd", label: "Kickoff Return Yards", category: "returns" },
  { abbrev: "KckRTD", label: "Kick Return Touchdowns", category: "returns" },
  { abbrev: "KickoffKickEPA", label: "Kickoff EPA", category: "kicking" },
  { abbrev: "KickoffPenaltyEPA", label: "Kickoff Penalty EPA", category: "specialteams" },
  { abbrev: "KickoffPenCmtdEPA", label: "Kickoff Penalties Committed EPA", category: "specialteams" },
  { abbrev: "KickoffReturnEPA", label: "Opponent Kickoff EPA", category: "kicking" },
  { abbrev: "KO", label: "Kickoffs", category: "kicking" },
  { abbrev: "KoIn20", label: "Kickoffs Inside 20", category: "kicking" },
  { abbrev: "KoIn25", label: "Kickoffs Inside 25", category: "kicking" },
  { abbrev: "KoR", label: "Kickoff Returns", category: "returns" },
  { abbrev: "KOR_EPA", label: "Kickoff Return EPA", category: "specialteams" },
  { abbrev: "KORLg", label: "Kickoff Return Long", category: "returns" },
  { abbrev: "KORLgTD", label: "Longest Kickoff Return Touchdown (Yards)", category: "returns" },
  { abbrev: "KoRTD", label: "Kickoff Return Touchdowns", category: "returns" },
  { abbrev: "KoRYd", label: "Kickoff Return Yards", category: "returns" },
  { abbrev: "KoTB", label: "Kickoff Touchback", category: "kicking" },
  { abbrev: "KOYd", label: "Kickoff Yards", category: "kicking" },
  { abbrev: "KPts", label: "Kicking Points", category: "kicking" },
  { abbrev: "KRADSP", label: "Average Drive Start Position After Kickoff Return Attempt", category: "returns" },
  { abbrev: "KRASP", label: "Average Position of Kickoff Return Attempts", category: "returns" },
  { abbrev: "KRFL", label: "Kickoff Return Fumbles Lost", category: "returns" },
  { abbrev: "KRFmb", label: "Kickoff Return Fumbles", category: "returns" },
  { abbrev: "KRFum", label: "Kickoff Return Fumbles", category: "returns" },
  { abbrev: "KRSP", label: "TEAM: Average Starting Field Position After Kickoff Return (or touchback for teams)", category: "returns" },
  { abbrev: "KRTD", label: "Kickoff Return Touchdowns", category: "returns" },
  { abbrev: "KRTD1stScr", label: "Kickoff Return Touchdowns That Were the 1st Score of the Game", category: "returns" },
  { abbrev: "LosTO", label: "Line Of Scrimmage Turnovers", category: "offense" },
  { abbrev: "MissFGRet", label: "Returns on Missed Field Goals", category: "specialteams" },
  { abbrev: "MissFGRetTD", label: "Return Touchdowns on Missed Field Goals", category: "specialteams" },
  { abbrev: "MissFGRetYds", label: "Return Yards on Missed Field Goals", category: "specialteams" },
  { abbrev: "NGSAvgDrpDepth", label: "Average Depth Of QB Dropback", category: "passing" },
  { abbrev: "NGSAvgMPHAtLOS", label: "Average Speed While Crossing Line Of Scrimmage With The Ball On Rush", category: "rushing" },
  { abbrev: "NGSAvgPassSpeed", label: "Average Speed Of Ball On Pass Plays", category: "passing" },
  { abbrev: "NGSAvgRouteMxMPH", label: "Average Max Speed During Route (MPH)", category: "receiving" },
  { abbrev: "NGSAvgTcklDist", label: "Average Distance Run On Tackles", category: "rushdefense" },
  { abbrev: "NGSAvgTimeToTckl", label: "Average Time From Snap To Tackle On Defensive Plays", category: "rushdefense" },
  { abbrev: "NGSAvgYdsPostClose", label: "Average Rush Yards Gained After Coming Within 1 Yard Of Nearest Defender", category: "rushing" },
  { abbrev: "NGSAvgYdsPreClose", label: "Average Rush Yards Gained Before Coming Within 1 Yard Of Nearest Defender", category: "rushing" },
  { abbrev: "NGSBadYACRec", label: "Receptions Where YAC Is 4 Or Fewer Yards Less Than Expected YAC", category: "receiving" },
  { abbrev: "NGSCush", label: "Average Yards Between Receiver And Defender They Are Lined Up Against", category: "receiving" },
  { abbrev: "NGSDepth1S", label: "Downfield Depth At 1 Sec", category: "receiving" },
  { abbrev: "NGSDepth2S", label: "Downfield Depth At 2 Sec", category: "receiving" },
  { abbrev: "NGSDepth3S", label: "Downfield Depth At 3 Sec", category: "receiving" },
  { abbrev: "NGSDepth4S", label: "Downfield Depth At 4 Sec", category: "receiving" },
  { abbrev: "NGSDfBoxSnaps", label: "Defensive snaps in box, using NGS coordinates", category: "defense" },
  { abbrev: "NGSDSnapHi", label: "Defensive snaps lined up at least 8 yds downfield", category: "defense" },
  { abbrev: "NGSDSnapOnLOS", label: "Defensive Snaps when within 2 yds of LOS", category: "defense" },
  { abbrev: "NGSGetOff", label: "Average Seconds From Snap To Crossing The LOS For Pass Rushers", category: "passrush" },
  { abbrev: "NGSGoodYACRec", label: "Receptions Where YAC Is 4+ Yards More Than Expected YAC", category: "receiving" },
  { abbrev: "NGSLcad", label: "Longest Completed Air Distance (2D)", category: "passing" },
  { abbrev: "NGSLOSSprint", label: "Rushes Where Speed >12 MPH Crossing The LOS", category: "rushing" },
  { abbrev: "NGSMaxMPHAtLOS", label: "Maximum Speed Reached While Crossing Line Of Scrimmage With The Ball On Rush", category: "rushing" },
  { abbrev: "NGSPctLOSSprint", label: "Percentage Of Rushes Where Speed >12 MPH Crossing The LOS", category: "rushing" },
  { abbrev: "NGSPressure", label: "QB Pressures By Pass Rusher", category: "passrush" },
  { abbrev: "NGSPressured", label: "Sacks + Pass Attempts With Nearest Defender Within 2 Yards At Attempt", category: "passing" },
  { abbrev: "NGSPressuredRate", label: "Rate Of Sacks + Pass Attempts With Nearest Defender Within 2 Yards At Attempt", category: "passing" },
  { abbrev: "NGSQBxYAC", label: "QB xYAC", category: "passing" },
  { abbrev: "NGSRec1D", label: "Receiving First Downs On Plays When NGS Expected Receiving Model At Time Of Catch Is Populated", category: "receiving" },
  { abbrev: "NGSRecTD", label: "Receiving Touchdowns On Plays When NGS Expected Receiving Model At Time Of Catch Is Populated", category: "receiving" },
  { abbrev: "NGSRoutes", label: "Pass Routes Run", category: "receiving" },
  { abbrev: "NGSRshYdsExp", label: "Average Rush Yards Expected", category: "rushing" },
  { abbrev: "NGSRshYdsOverExp", label: "Average Rush Yards Gained Over Expected", category: "rushing" },
  { abbrev: "NGSRush1D", label: "Rushing First Downs On Plays When NGS Expected Rushing Model At Time Of Handoff Is Populated", category: "rushing" },
  { abbrev: "NGSRushTD", label: "Rushing Touchdowns On Plays When NGS Expected Rushing Model At Time Of Handoff Is Populated", category: "rushing" },
  { abbrev: "NGSRushYdEff", label: "Rushing Yard Efficiency (Total distance traveled per rush yard gained)", category: "rushing" },
  { abbrev: "NGSSep", label: "Average Yards Between Target And Nearest Defender At Pass Arrival Time", category: "receiving" },
  { abbrev: "NGSSepAsTar", label: "Average Yards from Nearest Defender At Pass Arrival Time when Targeted", category: "receiving" },
  { abbrev: "NGSTghtWinAtt", label: "Tight Window Attempts", category: "passing" },
  { abbrev: "NGSTghtWinCmp", label: "Tight Window Completions", category: "passing" },
  { abbrev: "NGSTghtWinRec", label: "Tight Window Receptions", category: "receiving" },
  { abbrev: "NGSTghtWinTar", label: "Tight Window Targets", category: "receiving" },
  { abbrev: "NGSTLos", label: "Average Time Behind LOS On Rush Plays", category: "rushing" },
  { abbrev: "NGSxCOMP", label: "Expected Completion Percentage", category: "passing" },
  { abbrev: "NGSxRec1D", label: "Expected Receiving First Downs Per NGS Expected Receiving Model At Time Of Catch", category: "receiving" },
  { abbrev: "NGSxRecTD", label: "Expected Receiving Touchdowns Per NGS Expected Receiving Model At Time Of Catch", category: "receiving" },
  { abbrev: "NGSxRush1D", label: "Expected Rushing First Downs Per NGS Expected Rushing Model At Time Of Handoff", category: "rushing" },
  { abbrev: "NGSxRushTD", label: "Expected Rushing Touchdowns Per NGS Expected Rushing Model At Time Of Handoff", category: "rushing" },
  { abbrev: "NKOY", label: "Net Kickoff Yards", category: "kicking" },
  { abbrev: "NKRYds", label: "Non Kickoff Return Yards", category: "returns" },
  { abbrev: "NOffTD", label: "Non-Offensive Touchdowns", category: "defense" },
  { abbrev: "NonRec", label: "Non-Reception", category: "receiving" },
  { abbrev: "NPY", label: "Net Punt Yards", category: "punting" },
  { abbrev: "NtPsYds", label: "Net Passing Yards", category: "passing" },
  { abbrev: "NtYds", label: "Net Yards", category: "offense" },
  { abbrev: "Off4thMA", label: "Offensive 4th Down Makes - Attempts", category: "offense" },
  { abbrev: "OffAbortedEPA", label: "Offensive Aborted EPA", category: "offense" },
  { abbrev: "OffD", label: "Offensive Drives", category: "offense" },
  { abbrev: "OffensiveYards", label: "Total Yards (Pass Yards + Receiving Yards + Rush Yards)", category: "offense" },
  { abbrev: "OffFalSt", label: "Offensive False Start Penalties", category: "offense" },
  { abbrev: "OffFalStPenCmtdEPA", label: "Offensive False Start Penalties Committed EPA", category: "offense" },
  { abbrev: "OffFmbLEPA", label: "Offensive Fumble Lost EPA", category: "offense" },
  { abbrev: "OffIntEPA", label: "Offensive Interception EPA", category: "passing" },
  { abbrev: "OffPassPenaltyEPA", label: "Offensive Pass Penalty EPA", category: "passing" },
  { abbrev: "OffPassPenCmtdEPA", label: "Offensive Pass Penalties Committed EPA", category: "passing" },
  { abbrev: "OffPassSackEPA", label: "Offensive Sacked EPA", category: "passing" },
  { abbrev: "OffPassScrambleEPA", label: "Offensive Scramble EPA", category: "rushing" },
  { abbrev: "OffPassSpikeEPA", label: "Offensive Spike EPA", category: "passing" },
  { abbrev: "OffPassThrowEPA", label: "Offensive Throw EPA", category: "passing" },
  { abbrev: "OffPenaltyEPA", label: "Offensive Penalty EPA", category: "offense" },
  { abbrev: "OffPenCmtdEPA", label: "Offensive Penalties Committed EPA", category: "offense" },
  { abbrev: "OffPnYds", label: "Offensive Penalty Yards", category: "offense" },
  { abbrev: "OffPreSnapPenaltyEPA", label: "Offensive Pre Snap Penalty EPA", category: "offense" },
  { abbrev: "OffPreSnapPenCmtdEPA", label: "Offensive Pre Snap Penalties Committed EPA", category: "offense" },
  { abbrev: "OffRushEPA", label: "Offensive Rush EPA", category: "rushing" },
  { abbrev: "OffRushKneelEPA", label: "Offensive Kneel EPA", category: "rushing" },
  { abbrev: "OffRushNotQBEPA", label: "Offensive Non-QB Rush EPA", category: "rushing" },
  { abbrev: "OffRushPenaltyEPA", label: "Offensive Rush Penalty EPA", category: "rushing" },
  { abbrev: "OffRushPenCmtdEPA", label: "Offensive Rush Penalties Committed EPA", category: "rushing" },
  { abbrev: "OffSnapsExPen", label: "Offensive Snaps Excluding Plays Negated by Penalty", category: "offense" },
  { abbrev: "OffSuccess", label: "Successful Play Count on Offense", category: "offense" },
  { abbrev: "OffTD", label: "Offensive Touchdowns", category: "offense" },
  { abbrev: "OffTkl", label: "Tackles Made by the Offensive Team", category: "offense" },
  { abbrev: "OffTotalEPA", label: "Offensive EPA", category: "offense" },
  { abbrev: "OffTotalPassEPA", label: "Offensive Total Pass EPA", category: "passing" },
  { abbrev: "OffTotalRunEPA", label: "Offensive Total Run EPA", category: "rushing" },
  { abbrev: "OffTotalRushEPA", label: "Offensive Total Rush EPA - All Non-Dropbacks", category: "rushing" },
  { abbrev: "OffTovEPA", label: "Offensive Turnover EPA", category: "offense" },
  { abbrev: "OfPenNoPlay", label: "Offensive penalties in presnap or deadball situations", category: "offense" },
  { abbrev: "OfPenPassPl", label: "Offensive penalties on pass plays", category: "offense" },
  { abbrev: "OfPenRushPl", label: "Offensive penalties on rush plays", category: "offense" },
  { abbrev: "OfSnap", label: "Offensive Snaps", category: "offense" },
  { abbrev: "OfSnapWithPen", label: "Offensive Snaps Including Penalties", category: "offense" },
  { abbrev: "OfTargetEPA", label: "Offensive Team EPA When Targeted", category: "receiving" },
  { abbrev: "OnsK", label: "Onside Kickoff Attempt", category: "kicking" },
  { abbrev: "OnsKRcv", label: "Onside Kickoff Recovered", category: "kicking" },
  { abbrev: "OpAvFGA", label: "Average Opponent FG Attempt Distance", category: "kicking" },
  { abbrev: "OpBlkKck", label: "Own Kicks Blocked", category: "kicking" },
  { abbrev: "OpBlkXP", label: "Own Extra Point Blocked", category: "kicking" },
  { abbrev: "OpFC", label: "Opponent Fair Catch", category: "returns" },
  { abbrev: "OpFumL", label: "Opponent Fumbles Lost", category: "defense" },
  { abbrev: "OpKR30", label: "Opponent Kickoff Return 30+ Yards", category: "returns" },
  { abbrev: "OpKRMid", label: "Opponent Kickoff Returned Past Mid-Field", category: "returns" },
  { abbrev: "OpKRSP", label: "Opponent Average Starting Field Position After Kickoff Return", category: "returns" },
  { abbrev: "OppAvgDistTo1st", label: "Average Distance To First Down (On Defense)", category: "defense" },
  { abbrev: "OppFantPPG", label: "Opponent Offensive Fantasy Points Per Game", category: "defense" },
  { abbrev: "OppFantPPR", label: "Opponent Offensive Fantasy Points", category: "defense" },
  { abbrev: "OppFantPPRPPG", label: "Opponent Offensive Fantasy Points Per Game", category: "defense" },
  { abbrev: "OppFantPts", label: "Opponent Offensive Fantasy Points", category: "defense" },
  { abbrev: "OppKickFP", label: "Opponent Kicking Fantasy Points", category: "defense" },
  { abbrev: "OppKickFPPG", label: "Opponent Kicking Fantasy Points Per Game", category: "defense" },
  { abbrev: "OppManPlays", label: "Offensive Plays with Opponent in Man Coverage", category: "passing" },
  { abbrev: "OpPOT", label: "Opponent Points Off Turnovers", category: "defense" },
  { abbrev: "OppPassExpl", label: "Opponents Passing Explosives", category: "defense" },
  { abbrev: "OppPassFP", label: "Opponent Passing Fantasy Points", category: "defense" },
  { abbrev: "OppPassFPPG", label: "Opponent Passing Fantasy Points Per Game", category: "defense" },
  { abbrev: "OpPPG", label: "Points Allowed Per Game", category: "defense" },
  { abbrev: "OpPR", label: "Opponent Punt Returns", category: "returns" },
  { abbrev: "OppRecFP", label: "Opponent Receiving Fantasy Points", category: "defense" },
  { abbrev: "OppRecFPPG", label: "Opponent Receiving Fantasy Points Per Game", category: "defense" },
  { abbrev: "OppRecPPR", label: "Opponent Receiving Fantasy Points", category: "defense" },
  { abbrev: "OppRecPPRPG", label: "Opponent Receiving Fantasy Points Per Game", category: "defense" },
  { abbrev: "OpPRSP", label: "Opponent Starting Field Position After Punt Return", category: "returns" },
  { abbrev: "OppRushExpl", label: "Opponents Rushing Explosives", category: "defense" },
  { abbrev: "OppRushFP", label: "Opponent Rushing Fantasy Points", category: "defense" },
  { abbrev: "OppRushFPPG", label: "Opponent Rushing Fantasy Points Per Game", category: "defense" },
  { abbrev: "OpPts", label: "Points Allowed", category: "defense" },
  { abbrev: "OppZonePlays", label: "Offensive Plays with Opponent in Zone Coverage", category: "passing" },
  { abbrev: "OpRshYPG", label: "Opponent Rushing Yards Per Game", category: "rushdefense" },
  { abbrev: "OtFR", label: "Other Fumble Recoveries", category: "defense" },
  { abbrev: "OtTkl", label: "Other Tackles", category: "offense" },
  { abbrev: "P", label: "Punts", category: "punting" },
  { abbrev: "P-Ret", label: "Punt Returns", category: "returns" },
  { abbrev: "P-RTD", label: "Punt Return Touchdowns", category: "returns" },
  { abbrev: "P-RYd", label: "Punt Return Yards", category: "returns" },
  { abbrev: "P05", label: "Punts Taken Over Inside 5", category: "punting" },
  { abbrev: "P10", label: "Punts Taken Over Inside 10", category: "punting" },
  { abbrev: "P20", label: "Punts Inside 20", category: "punting" },
  { abbrev: "Pass_Rush", label: "Snaps as Pass Rusher", category: "defense" },
  { abbrev: "Pass1D", label: "Passing First Downs (Since 1991)", category: "passing" },
  { abbrev: "PassBlock", label: "Plays Pass Blocking", category: "offense" },
  { abbrev: "Passer", label: "Snaps as the Passer on Play", category: "offense" },
  { abbrev: "PassFP", label: "Passing Fantasy Points", category: "offense" },
  { abbrev: "PassRush", label: "Plays Pass Rushing", category: "passrush" },
  { abbrev: "PBkSnap", label: "Snaps When Role Was Pass Block", category: "blocking" },
  { abbrev: "PBlkd", label: "Own Punts Blocked", category: "punting" },
  { abbrev: "PctRushVs8Men", label: "Percentage Of Rush Attempts Versus 8+ Defenders In Box", category: "rushing" },
  { abbrev: "Pen_RoughingKicker", label: "Roughing Kicker Penalties", category: "specialteams" },
  { abbrev: "PenInCov", label: "Pass Interference & Defensive Holding Penalties in Coverage as Primary Pass Defender", category: "defense" },
  { abbrev: "PFF1stCtNoTkl", label: "Made 1st Contact With Ball Carrier, Didnt Make Tackle", category: "rushdefense" },
  { abbrev: "PFF2Man", label: "Defensive Plays in 2-Man Coverage", category: "passcoverage" },
  { abbrev: "PFFAtt", label: "PFF Pass Attempts", category: "offense" },
  { abbrev: "PFFAttLeft", label: "Pass Attempts To The Left", category: "offense" },
  { abbrev: "PFFAttMid", label: "Pass Attempts Between The Numbers", category: "offense" },
  { abbrev: "PFFAttRight", label: "Pass Attempts To The Right", category: "offense" },
  { abbrev: "PFFBlkrBeat", label: "Pass Blocker Beaten By Defender, No Pressure Allowed", category: "blocking" },
  { abbrev: "PFFBnchSnap", label: "Snaps When Receiver Lines Up In Stacked/Bunched Set", category: "receiving" },
  { abbrev: "PFFBracket", label: "Defensive Plays in Bracket Coverage", category: "passcoverage" },
  { abbrev: "PFFBtdPs", label: "Passes Batted By Defender", category: "passrush" },
  { abbrev: "PFFBtPs", label: "QB Batted Passes", category: "passing" },
  { abbrev: "PFFCausedFlg", label: "Drew Penalty On Opponent", category: "defense" },
  { abbrev: "PFFCover0", label: "Defensive Plays in Cover-0", category: "passcoverage" },
  { abbrev: "PFFCover1", label: "Defensive Plays in Cover-1", category: "passcoverage" },
  { abbrev: "PFFCover1D", label: "Defensive Plays in Cover-1 Double", category: "passcoverage" },
  { abbrev: "PFFCover2", label: "Defensive Plays in Cover-2", category: "passcoverage" },
  { abbrev: "PFFCover3", label: "Defensive Plays in Cover-3", category: "passcoverage" },
  { abbrev: "PFFCover3S", label: "Defensive Plays in Cover-3 Seam", category: "passcoverage" },
  { abbrev: "PFFCover6", label: "Defensive Plays in Cover-6", category: "passcoverage" },
  { abbrev: "PFFCreeper", label: "Creepers On Punt Returns", category: "returns" },
  { abbrev: "PFFCvgPen", label: "Pass Interference & Defensive Holding Penalties in Coverage as Primary Pass Defender", category: "passcoverage" },
  { abbrev: "PFFDefAtt", label: "Pass Attempts Against as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefComp", label: "Completions Against as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefIncomp", label: "Incompletions Against as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefIntPrim", label: "Defensive Interceptions as the Primary Pass Defender", category: "passcoverage" },
  { abbrev: "PFFDefPassAwayEPA", label: "Defensive Pass Throw Away EPA", category: "defense" },
  { abbrev: "PFFDefPs1st", label: "Pass First Downs Against As Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefPsrRt", label: "Passer Rating Against as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefPsTD", label: "Pass Touchdowns Against as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefPsYds", label: "Pass Yards Against as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDefYAC", label: "Defensive Yards After Catch Allowed as Primary Defender", category: "passcoverage" },
  { abbrev: "PFFDfPrimCvg", label: "Defender Had Primary Coverage On Target", category: "passcoverage" },
  { abbrev: "PFFDfSecCvg", label: "Defender Had Secondary Coverage On Target", category: "passcoverage" },
  { abbrev: "PFFDfStop", label: "Tackle Causing Unsuccessful Play For Offense", category: "rushdefense" },
  { abbrev: "PFFDrpInt", label: "Dropped Interceptions By Defender", category: "passcoverage" },
  { abbrev: "PFFFalseStart", label: "False Start Penalties (Accepted Only)", category: "offense" },
  { abbrev: "PFFGrdPassPl", label: "PFF Grade on Pass Plays", category: "offense" },
  { abbrev: "PffGrdRushPl", label: "PFF Grade on Rush Plays", category: "offense" },
  { abbrev: "PFFHitAllwd", label: "Hits Allowed", category: "blocking" },
  { abbrev: "PffHits", label: "Sacks + Other QB Hits By Pass Rusher", category: "passrush" },
  { abbrev: "PFFHrryAllwd", label: "Hurries Allowed", category: "blocking" },
  { abbrev: "PffHurry", label: "Hurries By Pass Rusher", category: "passrush" },
  { abbrev: "PFFKnockdowns", label: "Sacks + Hits", category: "passrush" },
  { abbrev: "PFFKODblTmd", label: "Doubled Teamed On Kickoff Coverage", category: "specialteams" },
  { abbrev: "PFFLateral", label: "Laterals", category: "offense" },
  { abbrev: "PFFLngSnpTm", label: "Long Snap Time", category: "punting" },
  { abbrev: "PFFManPlays", label: "Defensive Plays in Man Coverage", category: "passcoverage" },
  { abbrev: "PFFMissTkl", label: "Missed Tackles", category: "defense" },
  { abbrev: "PFFMissTklRsh", label: "Missed Tackles On Rush Attempts", category: "defense" },
  { abbrev: "PFFMotionSnap", label: "Plays With Motion At The Snap", category: "offense" },
  { abbrev: "PFFOffDbk", label: "Dropbacks Off the Field", category: "offense" },
  { abbrev: "PFFOffHold", label: "Offensive Holding Penalties (Accepted Only)", category: "offense" },
  { abbrev: "PFFOffPassAwayEPA", label: "Offensive Pass Throw Away EPA", category: "passing" },
  { abbrev: "PFFOffTgt", label: "Off-Target Pass Attempts", category: "passing" },
  { abbrev: "PFFOffxDbk", label: "Expected Dropbacks Off the Field", category: "passing" },
  { abbrev: "PFFOnDbk", label: "Dropbacks On the Field", category: "offense" },
  { abbrev: "PFFOnxDbk", label: "Expected Dropbacks On the Field", category: "passing" },
  { abbrev: "PFFOnxDDbk", label: "Expected Dropbacks as Defender on Field", category: "defense" },
  { abbrev: "PffOpDrpbk", label: "Defensive Snaps on Opponent Passing Plays", category: "defense" },
  { abbrev: "PFFOthPlays", label: "Defensive Plays not in Man or Zone Coverage", category: "passcoverage" },
  { abbrev: "PFFPassRushProd", label: "Pass Rushing Productivity", category: "passrush" },
  { abbrev: "PFFPassYdsLeft", label: "Pass Yards To The Left", category: "offense" },
  { abbrev: "PFFPassYdsMid", label: "Pass Yards Over The Middle", category: "offense" },
  { abbrev: "PFFPassYdsRight", label: "Pass Yards To The Right", category: "offense" },
  { abbrev: "PFFPresses", label: "Defensive Snaps Pressing Receiver After Snap", category: "passcoverage" },
  { abbrev: "PFFPressured", label: "Times a QB was Pressured by Opposing Defenses", category: "passing" },
  { abbrev: "PFFPrsrAllwd", label: "Pressures Allowed", category: "blocking" },
  { abbrev: "PFFPrsrs", label: "Pressures By Pass Rusher", category: "passrush" },
  { abbrev: "PFFPsBlkSnap", label: "Snaps As A Pass Blocker", category: "passrush" },
  { abbrev: "PFFPsBrkPrim", label: "Pass Breakups as Primary Pass Defender", category: "passcoverage" },
  { abbrev: "PFFPsBrkUp", label: "Pass Breakups", category: "passcoverage" },
  { abbrev: "PFFPsRshSnap", label: "Snaps As A Pass Rusher", category: "passrush" },
  { abbrev: "PFFPursuit", label: "Tackles Or Pressure Via Pursuit", category: "rushdefense" },
  { abbrev: "PFFQbDrops", label: "Pass Attempts Dropped By Target", category: "passing" },
  { abbrev: "PFFQBDrpInt", label: "QB Attempts That Were Dropped Interceptions by Defender", category: "passing" },
  { abbrev: "PFFQBHit", label: "Dropbacks On Which a QB Was Hit", category: "passing" },
  { abbrev: "PFFQBMvOfPckt", label: "QB Moved Off Intended Spot In Pocket", category: "passing" },
  { abbrev: "PFFQBPrsr", label: "QB Pressured", category: "passing" },
  { abbrev: "PFFQBReset", label: "Pass Attempts Where QB Resets Feet After Being In Motion", category: "passing" },
  { abbrev: "PFFQuarters", label: "Defensive Plays in Quarters Coverage", category: "passcoverage" },
  { abbrev: "PFFRcDrops", label: "Drops By Targeted Receivers", category: "receiving" },
  { abbrev: "PFFRcPressed", label: "Snaps When Pressed/Jammed At LOS", category: "receiving" },
  { abbrev: "PFFRecTklAvd", label: "Tackles Avoided On Receptions", category: "receiving" },
  { abbrev: "PFFRouteDepth", label: "Average Cut Depth of Route (Player Only)", category: "receiving" },
  { abbrev: "PFFRoutes", label: "Routes Run", category: "receiving" },
  { abbrev: "PFFRshTklAvd", label: "Tackles Avoided On Rushes", category: "rushing" },
  { abbrev: "PFFRtComebk", label: "Comeback Routes", category: "receiving" },
  { abbrev: "PFFRtCorner", label: "Corner Routes", category: "receiving" },
  { abbrev: "PFFRtCross", label: "Crossing Routes", category: "receiving" },
  { abbrev: "PFFRtFlare", label: "Flares", category: "receiving" },
  { abbrev: "PFFRtGo", label: "Go Routes", category: "receiving" },
  { abbrev: "PFFRtHBScrn", label: "HB Screens", category: "receiving" },
  { abbrev: "PFFRtHitch", label: "Hitches", category: "receiving" },
  { abbrev: "PFFRtIn", label: "In Routes", category: "receiving" },
  { abbrev: "PFFRtOut", label: "Out Routes", category: "receiving" },
  { abbrev: "PFFRtPivot", label: "Pivots", category: "receiving" },
  { abbrev: "PFFRtPost", label: "Post Routes", category: "receiving" },
  { abbrev: "PFFRtRcvrScrn", label: "WR/TE Screens", category: "receiving" },
  { abbrev: "PFFRtSlant", label: "Slants", category: "receiving" },
  { abbrev: "PFFRtWheel", label: "Wheels", category: "receiving" },
  { abbrev: "PFFRush", label: "Traditional Rushes", category: "offense" },
  { abbrev: "PFFRushLeft", label: "Rushes To The Left", category: "offense" },
  { abbrev: "PFFRushMid", label: "Rushes into the middle", category: "rushing" },
  { abbrev: "PFFRushNotMid", label: "Rushes not into the middle", category: "rushing" },
  { abbrev: "PFFRushRight", label: "Rushes To The Right", category: "offense" },
  { abbrev: "PFFRushYds", label: "Rush Yards on Traditional Rushes", category: "offense" },
  { abbrev: "PFFRushYdsLeft", label: "Rush Yards To The Left", category: "offense" },
  { abbrev: "PFFRushYdsMid", label: "Rush Yards Up The Middle", category: "offense" },
  { abbrev: "PFFRushYdsRight", label: "Rush Yards To The Right", category: "offense" },
  { abbrev: "PFFScrnBlkr", label: "Block Attempts On Screen Pass", category: "blocking" },
  { abbrev: "PFFShiftPlay", label: "Snaps With A Shift Pre-snap", category: "offense" },
  { abbrev: "PFFSkAllwd", label: "Sacks Allowed", category: "blocking" },
  { abbrev: "PFFSnapsBkfld", label: "Total Backfield Snaps", category: "rushing" },
  { abbrev: "PFFSnapsSlot", label: "Total Snaps lined up in Slot", category: "offense" },
  { abbrev: "PFFSnapsTE", label: "Total Snaps lined up as TE", category: "offense" },
  { abbrev: "PFFSnapsWide", label: "Total Snaps lined up as wideout", category: "offense" },
  { abbrev: "PffTar", label: "Targets", category: "receiving" },
  { abbrev: "PffTime2Prsr", label: "Time to Pressure on Defense", category: "passrush" },
  { abbrev: "PffTime2PrsrAllwd", label: "Time to Pressure Allowed on Offense", category: "passing" },
  { abbrev: "PffTime2Sack", label: "Time to Sack on Defense", category: "passrush" },
  { abbrev: "PFFTklAvoid", label: "Tackles Avoided", category: "rushing" },
  { abbrev: "PFFZonePlays", label: "Defensive Plays in Zone Coverage", category: "passcoverage" },
  { abbrev: "PIn20", label: "Punts Downed Inside the Opponent 20-Yard Line", category: "specialteams" },
  { abbrev: "PKOSP", label: "Average Post Kickoff Opponent Start Position", category: "kicking" },
  { abbrev: "Pl0Neg", label: "Zero or Negative Yard Plays", category: "offense" },
  { abbrev: "PlAdv", label: "Play To Advance (Not Kneels or Spikes)", category: "offense" },
  { abbrev: "PlayClockHudlBrk", label: "Average Play Clock at Huddle Break", category: "offense" },
  { abbrev: "PlayClockLineSet", label: "Average Play Clock at Line Set", category: "offense" },
  { abbrev: "Plays", label: "Offensive LOS Plays (Does Not Include FGA Or Punts)", category: "offense" },
  { abbrev: "Pnt", label: "Punts", category: "punting" },
  { abbrev: "PntTB", label: "Punt Touchbacks", category: "punting" },
  { abbrev: "PntYds", label: "Punt Yards", category: "punting" },
  { abbrev: "PPG", label: "Points Scored Per Game", category: "offense" },
  { abbrev: "PPOSP", label: "Average Post Punt Opponent Start Position", category: "punting" },
  { abbrev: "PR", label: "Punt Returns", category: "returns" },
  { abbrev: "PRFL", label: "Punt Return Fumbles Lost", category: "returns" },
  { abbrev: "PRFmb", label: "Punt Return Fumbles", category: "returns" },
  { abbrev: "PRFum", label: "Punt Return Fumbles", category: "returns" },
  { abbrev: "PrimPos", label: "Scouting Position", category: "player" },
  { abbrev: "PRLg", label: "Punt Return Long", category: "returns" },
  { abbrev: "PRLgTD", label: "Longest Punt Return Touchdown (Yards)", category: "returns" },
  { abbrev: "PRSP", label: "Punt Return Average Starting Field Position (Includes Touchbacks & Fair Catches For Teams Only)", category: "returns" },
  { abbrev: "PRTD", label: "Punt Return Touchdowns", category: "returns" },
  { abbrev: "PRTD1stScr", label: "Punt Return Touchdowns That Were the 1st Score of the Game", category: "returns" },
  { abbrev: "PRYd", label: "Punt Return Yards", category: "returns" },
  { abbrev: "PsDfnd", label: "Passes Defended", category: "passcoverage" },
  { abbrev: "PsLg", label: "Passing Long", category: "passing" },
  { abbrev: "PsLgTD", label: "Longest Passing Touchdown (Yards)", category: "passing" },
  { abbrev: "PsrRt", label: "NFL Passer Rating", category: "passing" },
  { abbrev: "PsRshTD", label: "Pass + Rush TD", category: "passing" },
  { abbrev: "PsTD", label: "Pass Touchdowns", category: "passing" },
  { abbrev: "PsTD1stScr", label: "Passing Touchdowns That Were the 1st Score of the Game", category: "passing" },
  { abbrev: "PsYds", label: "Passing Yards", category: "passing" },
  { abbrev: "PtIn10", label: "Punts Taken Over Inside the 10", category: "punting" },
  { abbrev: "PtLg", label: "Punting Long", category: "punting" },
  { abbrev: "Pts", label: "Points Scored", category: "offense" },
  { abbrev: "Punt_Ret_EPA", label: "Punt Returner EPA", category: "offense" },
  { abbrev: "PuntEPA", label: "Punter EPA", category: "specialteams" },
  { abbrev: "PuntKickEPA", label: "Punt EPA", category: "punting" },
  { abbrev: "PuntOpps", label: "Punt Formations", category: "specialteams" },
  { abbrev: "PuntPenaltyEPA", label: "Punt Penalty EPA", category: "specialteams" },
  { abbrev: "PuntPenCmtdEPA", label: "Punt Penalties Committed EPA", category: "specialteams" },
  { abbrev: "PuntReturnEPA", label: "Opponent Punt EPA", category: "punting" },
  { abbrev: "QBHit", label: "Dropbacks On Which a QB Was Hit", category: "passing" },
  { abbrev: "QBLoss", label: "QB Loss As Starter", category: "passing" },
  { abbrev: "QBStart", label: "Games Started As QB", category: "passing" },
  { abbrev: "QBTie", label: "QB Ties As Starter", category: "passing" },
  { abbrev: "QBWin", label: "QB Win As Starter", category: "passing" },
  { abbrev: "QBYAC", label: "Yards After Catch On QB Completions", category: "passing" },
  { abbrev: "RBkSnap", label: "Snaps When Role Was Run Block", category: "blocking" },
  { abbrev: "Rec", label: "Receptions", category: "receiving" },
  { abbrev: "Rec1D", label: "Receiving First Downs", category: "receiving" },
  { abbrev: "RecFL", label: "Receiving Fumbles Lost", category: "receiving" },
  { abbrev: "RecFPHalf", label: "Receiving Half-PPR Fantasy Points", category: "offense" },
  { abbrev: "RecFPPPR", label: "Receiving PPR Fantasy Points", category: "offense" },
  { abbrev: "RecFPStan", label: "Receiving Fantasy Points in Standard Scoring", category: "offense" },
  { abbrev: "RecFum", label: "Receiving Fumbles", category: "receiving" },
  { abbrev: "RecLg", label: "Receiving Long", category: "receiving" },
  { abbrev: "RecLgTD", label: "Longest Receiving Touchdown (Yards)", category: "receiving" },
  { abbrev: "RecRB", label: "Receptions By Running Backs", category: "offense" },
  { abbrev: "RecTD", label: "Receiving Touchdowns", category: "receiving" },
  { abbrev: "RecTDRB", label: "Receiving Touchdowns By Running Backs", category: "offense" },
  { abbrev: "RecTDTE", label: "Receiving Touchdowns By Tight Ends", category: "offense" },
  { abbrev: "RecTDWR", label: "Receiving Touchdowns By Wide Receivers", category: "offense" },
  { abbrev: "RecTE", label: "Receptions By Tight Ends", category: "offense" },
  { abbrev: "RecWR", label: "Receptions By Wide Receivers", category: "offense" },
  { abbrev: "RecYds", label: "Receiving Yards", category: "receiving" },
  { abbrev: "RecYdsRB", label: "Receiving Yards By Running Backs", category: "offense" },
  { abbrev: "RecYdsTE", label: "Receiving Yards By Tight Ends", category: "offense" },
  { abbrev: "RecYdsWR", label: "Receiving Yards By Wide Receivers", category: "offense" },
  { abbrev: "RecYPG", label: "Receiving Yards Per Game", category: "receiving" },
  { abbrev: "RnNeg", label: "Negative Yard Rushes", category: "rushing" },
  { abbrev: "Routes", label: "Pass Routes Run", category: "receiving" },
  { abbrev: "Rs0Neg", label: "Zero or Negative Yard Rushes", category: "rushing" },
  { abbrev: "Rsh_DesRun", label: "Rushes (Excludes Scrambles and Kneels)", category: "offense" },
  { abbrev: "Rsh1st", label: "Rushing First Downs", category: "rushing" },
  { abbrev: "RshAdjYACt", label: "Adjusted Yards After Contact On Rushes", category: "rushing" },
  { abbrev: "RshAdjYBCt", label: "Adjusted Yards Before Contact On Rushes", category: "rushing" },
  { abbrev: "RshCmp", label: "Rushes + Completions", category: "offense" },
  { abbrev: "RshCmpPG", label: "Rushes + Completions Per Game", category: "offense" },
  { abbrev: "RshFL", label: "Rushing Fumbles Lost (Not Including Sacks)", category: "rushing" },
  { abbrev: "RshFmb", label: "Rushing Fumbles (Not Including Sacks)", category: "rushing" },
  { abbrev: "RshFum", label: "Rushing Fumbles (Not Including Sacks)", category: "rushing" },
  { abbrev: "RshLg", label: "Rushing Long", category: "rushing" },
  { abbrev: "RshLgTD", label: "Longest Rushing Touchdown (Yards)", category: "rushing" },
  { abbrev: "RshNoSk", label: "Rushes Not Including Sacks", category: "rushing" },
  { abbrev: "RshRcFL", label: "Rushing or Receiving Fumbles Lost (Not Including Sacks)", category: "offense" },
  { abbrev: "RshRcFmb", label: "Rushing or Receiving Fumbles (Not Including Sacks)", category: "offense" },
  { abbrev: "RshTD", label: "Rushing Touchdowns", category: "rushing" },
  { abbrev: "RshTD1stScr", label: "Rushing Touchdowns That Were the 1st Score of the Game", category: "rushing" },
  { abbrev: "RshYACt", label: "Yards After Contact On Rushes", category: "rushing" },
  { abbrev: "RshYBCt", label: "Yards Before Contact On Rushes", category: "rushing" },
  { abbrev: "RshYds", label: "Rushing Yards", category: "rushing" },
  { abbrev: "RshYds_DesRun", label: "Rushing Yards on Designed Runs Only", category: "offense" },
  { abbrev: "RshYds1Q", label: "First Quarter Rushing Yards", category: "rushing" },
  { abbrev: "RshYds4Q", label: "Fourth Quarter Rushing Yards", category: "rushing" },
  { abbrev: "RshYPG1Q", label: "Rushing Yards Per Game In First Quarter", category: "rushing" },
  { abbrev: "RshYPG4Q", label: "Rushing Yards Per Game In Fourth Quarter", category: "rushing" },
  { abbrev: "RunBlock", label: "Plays Run Blocking", category: "offense" },
  { abbrev: "RunnerSnaps", label: "Plays as the Ball Carrier on a Run Play", category: "offense" },
  { abbrev: "Runs_Designed", label: "Designed Run Plays", category: "offense" },
  { abbrev: "Runs_DesignedAgt", label: "Designed Run Plays Against Defense", category: "defense" },
  { abbrev: "Rush", label: "Rushes (Includes Scrambles and Kneels)", category: "rushing" },
  { abbrev: "Rush1D", label: "Rushing First Downs (Since 1991)", category: "rushing" },
  { abbrev: "RushFP", label: "Rushing Fantasy Points", category: "offense" },
  { abbrev: "RZDr", label: "Red Zone Drives", category: "offense" },
  { abbrev: "RZRecTD", label: "Receiving Touchdowns on Plays in the Red Zone", category: "receiving" },
  { abbrev: "RZRush", label: "Rushes in the Red Zone", category: "rushing" },
  { abbrev: "RZRushTD", label: "Rushing Touchdowns in the Red Zone", category: "rushing" },
  { abbrev: "RZTar", label: "Targets on Plays in the Red Zone", category: "receiving" },
  { abbrev: "RZTD", label: "Red Zone Touchdowns", category: "offense" },
  { abbrev: "RZTO", label: "Red Zone Turnovers", category: "offense" },
  { abbrev: "Sack", label: "QB Sacks", category: "passing" },
  { abbrev: "Sack3D", label: "QB Sacks On Third Down", category: "passing" },
  { abbrev: "Sack4Q", label: "QB Sacks In The Fourth Quarter", category: "passing" },
  { abbrev: "SckFL", label: "Sack Fumbles Lost", category: "passing" },
  { abbrev: "SckFum", label: "Sack Fumbles", category: "passing" },
  { abbrev: "Scrmbl", label: "Scrambles", category: "passing" },
  { abbrev: "ScrmblYds", label: "Scramble Yards", category: "passing" },
  { abbrev: "ScrTD", label: "Scrimmage Touchdowns", category: "offense" },
  { abbrev: "ScrYds", label: "Yards from Scrimmage (Rush Yards + Rec Yards)", category: "offense" },
  { abbrev: "ScrYPG", label: "Scrimmage Yards Per Game", category: "offense" },
  { abbrev: "Sfty", label: "Defensive Safeties", category: "defense" },
  { abbrev: "Sfty1stScr", label: "Defensive Safeties That Were the 1st Score of the Game", category: "defense" },
  { abbrev: "ShtgnYPR", label: "Shotgun Yards per Rush", category: "rushing" },
  { abbrev: "SkFF", label: "Forced Fumbles on Sacks", category: "passrush" },
  { abbrev: "SkYds", label: "Sack Yards", category: "passing" },
  { abbrev: "Solo", label: "Solo Defensive Tackles", category: "defense" },
  { abbrev: "ST-Ret", label: "Special Team Kickoff and Punt Returns", category: "specialteams" },
  { abbrev: "STBlockRetEPA", label: "Special Teams Block or Return EPA", category: "returns" },
  { abbrev: "STBlockRetTovEPA", label: "Special Teams Block or Return Turnover EPA", category: "returns" },
  { abbrev: "STEPA", label: "Special Teams EPA", category: "specialteams" },
  { abbrev: "STFalSt", label: "Special Teams False Start Penalties", category: "specialteams" },
  { abbrev: "STFalStPenCmtdEPA", label: "Special Teams False Start Penalties Committed EPA", category: "specialteams" },
  { abbrev: "STFF", label: "Special Teams Forced Fumbles", category: "specialteams" },
  { abbrev: "STFR", label: "Special Teams Fumble Recoveries", category: "specialteams" },
  { abbrev: "STKickEPA", label: "Special Teams Kick EPA", category: "specialteams" },
  { abbrev: "STKickTovEPA", label: "Special Teams Kick Turnover EPA", category: "kicking" },
  { abbrev: "STPenaltyEPA", label: "Special Teams Penalty EPA", category: "specialteams" },
  { abbrev: "STPenCmtdEPA", label: "Special Teams Penalties Committed EPA", category: "specialteams" },
  { abbrev: "STPlay", label: "Special Teams Plays", category: "specialteams" },
  { abbrev: "StripSack", label: "Strip Sacks", category: "defense" },
  { abbrev: "STSnap", label: "Special Teams Snaps", category: "specialteams" },
  { abbrev: "STTD", label: "Special Teams Touchdowns", category: "specialteams" },
  { abbrev: "STTkl", label: "Tackles Made by the Special Teams", category: "specialteams" },
  { abbrev: "STTklAst", label: "Special Teams Assisted Tackles", category: "specialteams" },
  { abbrev: "STTklSolo", label: "Special Teams Solo Tackles", category: "specialteams" },
  { abbrev: "STTovEPA", label: "Special Teams Turnover EPA", category: "specialteams" },
  { abbrev: "Success", label: "Successful Play Count", category: "offense" },
  { abbrev: "SuccessPlays", label: "Successful Offensive Plays", category: "offense" },
  { abbrev: "Takeaways", label: "Interceptions + Recoveries of Opponent Fumbles", category: "defense" },
  { abbrev: "Tar", label: "Targets", category: "receiving" },
  { abbrev: "Tar01S", label: "Targets Thrown At or Before 1 Sec", category: "receiving" },
  { abbrev: "Tar12S", label: "Targets Thrown Between 1 Sec and 2 Sec", category: "receiving" },
  { abbrev: "Tar23S", label: "Targets Thrown Between 2 Sec and 3 Sec", category: "receiving" },
  { abbrev: "Tar34S", label: "Targets Thrown Between 3 Sec and 4 Sec", category: "receiving" },
  { abbrev: "Tar45S", label: "Targets Thrown Between 4 Sec and 5 Sec", category: "receiving" },
  { abbrev: "TarInt", label: "Target Interceptions", category: "receiving" },
  { abbrev: "TarRB", label: "Running Back Targets", category: "passing" },
  { abbrev: "TarTE", label: "Tight End Targets", category: "passing" },
  { abbrev: "TarWR", label: "Wide Receiver Targets", category: "passing" },
  { abbrev: "TD", label: "Touchdowns", category: "offense" },
  { abbrev: "TDRsp", label: "TD (PassTD + RshTD + RecTD + RetTD)", category: "offense" },
  { abbrev: "TDScrd", label: "Touchdowns Scored", category: "offense" },
  { abbrev: "TFL", label: "Tackled for a Loss", category: "rushdefense" },
  { abbrev: "TFL_Run", label: "Tackles For a Loss on Runs", category: "defense" },
  { abbrev: "TkFL", label: "Overall TFLs (excluding Sacks)", category: "offense" },
  { abbrev: "Tkl", label: "Tackles", category: "defense" },
  { abbrev: "TklPass", label: "Tackles on pass plays", category: "defense" },
  { abbrev: "TklRush", label: "Tackles on designed rush plays", category: "rushdefense" },
  { abbrev: "TmDefFmbLEPA", label: "Team Defensive Fumble Lost EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefIntEPA", label: "Team Defensive Interception EPA (While On Field)", category: "passcoverage" },
  { abbrev: "TmDefPassAwayEPA", label: "Team Defensive Pass Throw Away EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefPassSackEPA", label: "Team Defensive Sack EPA (While On Field)", category: "offense" },
  { abbrev: "TmDefPassScrambleEPA", label: "Team Defensive Scramble EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefPassThrowEPA", label: "Team Defensive Throw EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefPenaltyEPA", label: "Team Defensive Penalty EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefSnapEPA", label: "Team Defensive EPA (While On Field)", category: "offense" },
  { abbrev: "TmDefSnapScs", label: "Team Defensive Success Count (While On Field)", category: "defense" },
  { abbrev: "TmDefTotalPassEPA", label: "Team Defensive Total Pass EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefTotalRunEPA", label: "Team Defensive Total Run EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefTotalRushEPA", label: "Team Defensive Total Rush EPA (While On Field)", category: "defense" },
  { abbrev: "TmDefTovEPA", label: "Team Defensive Turnover EPA (While On Field)", category: "defense" },
  { abbrev: "TmFGAEPA", label: "FGA EPA", category: "kicking" },
  { abbrev: "TmKickoffKickEPA", label: "Kickoff EPA", category: "kicking" },
  { abbrev: "TmKickoffReturnEPA", label: "Kickoff Return EPA", category: "returns" },
  { abbrev: "TmOffFmbLEPA", label: "Team Offensive Fumble Lost EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffIntEPA", label: "Team Offensive Interception EPA (While On Field)", category: "passing" },
  { abbrev: "TmOffPassAwayEPA", label: "Team Offensive Pass Throw Away EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffPassSackEPA", label: "Team Offensive Sacked EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffPassScrambleEPA", label: "Team Offensive Scramble EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffPassThrowEPA", label: "Team Offensive Throw EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffPenaltyEPA", label: "Team Offensive Penalty EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffSnapEPA", label: "Team Offensive EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffSnapScs", label: "Team Offensive Success Count (While On Field)", category: "offense" },
  { abbrev: "TmOffTotalPassEPA", label: "Team Offensive Total Pass EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffTotalRecEPA", label: "Team Offensive Total Reception EPA", category: "receiving" },
  { abbrev: "TmOffTotalRunEPA", label: "Team Offensive Total Run EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffTotalRushEPA", label: "Team Offensive Total Rush EPA (While On Field)", category: "offense" },
  { abbrev: "TmOffTotalTargetEPA", label: "Team Offensive Total Target EPA", category: "offense" },
  { abbrev: "TmOffTovEPA", label: "Team Offensive Turnover EPA (While On Field)", category: "offense" },
  { abbrev: "TmPffDfSnapOff", label: "Team Defensive Snaps with Player Off", category: "defense" },
  { abbrev: "TmPsRushOn", label: "Team Pass Rush with Player On", category: "defense" },
  { abbrev: "TmPuntKickEPA", label: "Punt EPA", category: "punting" },
  { abbrev: "TmPuntReturnEPA", label: "Punt Return EPA", category: "returns" },
  { abbrev: "TmSTSnapEPA", label: "Team Special Teams EPA (While On Field)", category: "specialteams" },
  { abbrev: "TmXPAEPA", label: "XPA EPA", category: "kicking" },
  { abbrev: "TO", label: "Turnovers", category: "offense" },
  { abbrev: "TotalEPA_Block", label: "Total EPA Credit for Blocking on Plays", category: "offense" },
  { abbrev: "TotalEPA_Pass", label: "Total EPA for a QB on Dropbacks", category: "offense" },
  { abbrev: "TotalEPA_QB", label: "Total EPA for QBs (Including Rushing Stats)", category: "offense" },
  { abbrev: "TotalEPA_RB", label: "Total EPA for a Running Back (Designed Runs + Targets)", category: "offense" },
  { abbrev: "TotalEPA_Rec", label: "Total EPA on Targets", category: "offense" },
  { abbrev: "TotalEPA_Rush", label: "Total EPA for on Carries", category: "offense" },
  { abbrev: "TotalEPAQB", label: "Total EPA for QBs (Including Rushing Stats)", category: "offense" },
  { abbrev: "TotalPPG", label: "Total Points Per Game", category: "offense" },
  { abbrev: "TotRYd", label: "Total Return Yards", category: "returns" },
  { abbrev: "TotYds", label: "Total Yards (Pass Yards + Rush Yards)", category: "offense" },
  { abbrev: "Touches", label: "Touches", category: "offense" },
  { abbrev: "TrickEPA", label: "EPA on Trick Plays", category: "offense" },
  { abbrev: "UnAirYds", label: "Unrealized Air Yards", category: "receiving" },
  { abbrev: "UnAirYdsQB", label: "Quarterback Unrealized Air Yards", category: "passing" },
  { abbrev: "XP", label: "Extra Points Made", category: "kicking" },
  { abbrev: "XP_EPA", label: "XP EPA", category: "specialteams" },
  { abbrev: "XPA", label: "Extra Point Attempts", category: "kicking" },
  { abbrev: "XPAPenaltyEPA", label: "Extra Point Attempt Penalty EPA", category: "specialteams" },
  { abbrev: "XPAPenCmtdEPA", label: "Extra Point Attempt Penalties Committed EPA", category: "specialteams" },
  { abbrev: "XPBlk", label: "XPA Block", category: "kicking" },
  { abbrev: "XPBlkd", label: "XPA Blocked", category: "kicking" },
  { abbrev: "XPKickBlockRetEPA", label: "Opponent XPA EPA", category: "kicking" },
  { abbrev: "XPKickEPA", label: "XPA EPA", category: "kicking" },
  { abbrev: "YAC", label: "Yards After The Catch", category: "receiving" },
  { abbrev: "YBContOnField", label: "Yards Before Contact/Att While On Field", category: "offense" },
  { abbrev: "Yds", label: "Total Yards of Offense", category: "offense" },
  { abbrev: "YPR", label: "Rushing Yards / Att on Designed Runs (No Scrambles/Sacks/Kneels)", category: "offense" },
];
